Repository dileepadev/dileepa.dev, pull requests merged in 2023-11, with the labels that each got.

#4 feat(main): Develop Version 1.0.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  public/banner.webp
  public/profile_picture_circle.png
  public/svg/coventry.svg
  public/svg/ddst.svg
  public/svg/ewd.svg
  public/svg/fosslk.svg
  public/svg/gdglk.svg
  public/svg/hashnode.svg
  public/svg/mlsa.svg
  public/svg/mmc.svg
  public/svg/msft.svg
  public/svg/nibm.svg
  public/svg/nibmcs.svg
  public/svg/nibmfossc.svg
  public/svg/youtube.svg
  src/app/about/layout.tsx
  src/app/about/page.tsx
  src/app/api/email/route.ts
  src/app/api/welcome/route.ts
  src/app/connect/layout.tsx
  src/app/connect/page.tsx
  src/app/education/layout.tsx
  src/app/education/page.tsx
  src/app/experience/layout.tsx
  src/app/experience/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/media/layout.tsx
  src/app/media/page.jsx
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/ItemCards.tsx
  src/components/Logo.tsx
  src/components/NavBar.tsx
  src/components/SectionTitle.tsx
  src/components/SocialMediaBar.tsx
  src/components/email-template.tsx
  src/components/icons/IconClose.tsx
  src/components/icons/IconMenu.tsx
  src/components/icons/IconMoon.tsx
  src/components/icons/IconSun.tsx
  src/components/theme/ThemeSwitcher.tsx
  src/components/theme/themeProvider.tsx
  src/components/toast.tsx
  src/config/metaData.ts
  src/config/siteInfo.ts
  src/constants/fontStyle.ts
  src/constants/links.ts
  src/constants/textData.ts
  src/types/interfaces.ts
  src/utils/formUtils.ts
  tailwind.config.ts
Labels: enhancement, feature request

#5 docs(main): Add new guidelines
  BRANCH_NAMING_GUIDELINES.md
  CHANGELOG.md
  CONTRIBUTING.md
  PULL_REQUEST_GUIDELINES.md
  README.md
Labels: documentation

#7 fix(dev): Link cards to a new username [#6]
  package.json
  public/profile.png
  public/profile.webp
  public/profile_picture.jpg
  public/svg/mms.svg
  src/app/favicon.ico
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/ItemCards.tsx
  src/constants/links.ts
  src/constants/textData.ts
Labels: bug

#8 fix(main): Link cards to a new username [#6]
  package.json
  public/profile.png
  public/profile.webp
  public/profile_picture.jpg
  public/svg/mms.svg
  src/app/favicon.ico
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/ItemCards.tsx
  src/constants/links.ts
  src/constants/textData.ts
Labels: bug

#9 docs(main): Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
